#!/usr/bin/env bash

# CONSTANTS:start
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'
DIR=$(dirname "$0")
# CONSTANTS:end

# The location of the Ansible inventory file to be used on the test.
# NOTE: INVENTORY file is automatically generated by Vagrant.
INVENTORY="${DIR}/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory"

# The filename of the Ansible playbook to be used on the test.
# NOTE: PLAYBOOK must be the same value as defined in the Vagrantfile.
PLAYBOOK="${DIR}/vagrant.yml"

# The idempotence pass criteria.
PASS_CRITERIA="changed=0.*failed=0"
